//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netmefy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bt_notificaciones
    {
        public int usuario_sk { get; set; }
        public int cliente_sk { get; set; }
        public int notificacion_sk { get; set; }
        public System.DateTime tiempo_sk { get; set; }
        public Nullable<int> ot_id { get; set; }
    
        public virtual lk_notificacion lk_notificacion { get; set; }
        public virtual lk_tiempo lk_tiempo { get; set; }
        public virtual usuario lk_usuario { get; set; }
    }
}
