//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netmefy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bt_solicitudes
    {
        public int os_id { get; set; }
        public int cliente_sk { get; set; }
        public System.DateTime fh_creacion { get; set; }
        public Nullable<System.DateTime> fh_cierre { get; set; }
        public int tipo { get; set; }
        public string descripcion { get; set; }
    
        public virtual cliente lk_cliente { get; set; }
        public virtual lk_tiempo lk_tiempo { get; set; }
        public virtual lk_tiempo lk_tiempo1 { get; set; }
    }
}
