//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netmefy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bt_tests
    {
        public int test_id { get; set; }
        public int cliente_sk { get; set; }
        public System.DateTime tiempo_sk { get; set; }
        public Nullable<int> ot_id { get; set; }
        public int flag_instalacion { get; set; }
        public string comentario { get; set; }
        public Nullable<int> vel_mb_medidos { get; set; }
        public Nullable<int> potencia_recep { get; set; }
        public Nullable<int> flag_clabeado_nuevo { get; set; }
        public Nullable<int> flag_modem_ok { get; set; }
    
        public virtual bt_ord_trabajo bt_ord_trabajo { get; set; }
        public virtual cliente lk_cliente { get; set; }
        public virtual lk_tiempo lk_tiempo { get; set; }
    }
}
