//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netmefy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dispositivo
    {
        public int cliente_sk { get; set; }
        public int router_sk { get; set; }
        public int dispositivo_sk { get; set; }
        public string dispositivo_mac { get; set; }
        public string dispositivo_ip { get; set; }
        public byte[] dispositivo_foto { get; set; }
        public string dispositivo_apodo { get; set; }
        public string dispositivo_tipo { get; set; }
        public int dispositivo_bloq { get; set; }
    
        public virtual router lk_cliente_router { get; set; }
    }
}
