//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netmefy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lk_cliente_router
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lk_cliente_router()
        {
            this.lk_dispositivo = new HashSet<lk_dispositivo>();
            this.lk_web = new HashSet<lk_web>();
        }
    
        public int cliente_sk { get; set; }
        public int router_sk { get; set; }
        public string router_modelo { get; set; }
        public Nullable<int> router_activo { get; set; }
        public string router_ssid { get; set; }
        public string router_psw { get; set; }
    
        public virtual cliente lk_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lk_dispositivo> lk_dispositivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lk_web> lk_web { get; set; }
    }
}
