//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netmefy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int log_sk { get; set; }
        public int cliente_sk { get; set; }
        public int log_tipo { get; set; }
        public string log_desc { get; set; }
        public System.DateTime fechahora { get; set; }
    }
}
