//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netmefy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class token
    {
        public int id { get; set; }
        public int sk_entidad { get; set; }
        public bool es_cliente { get; set; }
        public bool es_tecnico { get; set; }
        public string tokenid { get; set; }
        public int usuario_sk { get; set; }
    }
}
