//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netmefy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.bt_notificaciones = new HashSet<bt_notificaciones>();
            this.lk_entidad = new HashSet<lk_entidad>();
        }
    
        public int usuario_sk { get; set; }
        public int cliente_sk { get; set; }
        public string usuario_nombre { get; set; }
        public string usuario_sexo { get; set; }
        public Nullable<int> usuario_edad { get; set; }
        public byte[] usuario_foto { get; set; }
        public string usuario_email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bt_notificaciones> bt_notificaciones { get; set; }
        public virtual cliente lk_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lk_entidad> lk_entidad { get; set; }
    }
}
