//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netmefy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_alertas
    {
        public Nullable<double> latitud { get; set; }
        public Nullable<double> longitud { get; set; }
        public string nombreDeLocalidad { get; set; }
        public Nullable<int> cantidadDeUsuariosAfectados { get; set; }
    }
}
