//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netmefy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_calificacion_tecnico
    {
        public int sk { get; set; }
        public string id { get; set; }
        public string psw { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public Nullable<decimal> calificacion { get; set; }
        public int ot_asignadas { get; set; }
        public int ot_cerradas { get; set; }
    }
}
