//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netmefy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_isp_oss
    {
        public int id { get; set; }
        public string numeroDeCliente { get; set; }
        public string nombreDeCliente { get; set; }
        public string tipoDeOrden { get; set; }
        public string fechaCreacion { get; set; }
        public string fechaFinalizacion { get; set; }
        public string estado { get; set; }
    }
}
