//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netmefy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_notificaciones
    {
        public string tipo { get; set; }
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string fecha { get; set; }
        public Nullable<int> cantidadDeUsuariosSuscriptos { get; set; }
    }
}
