//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netmefy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ot_porc_quejas
    {
        public int localidad_sk { get; set; }
        public Nullable<int> q_cli_quejas { get; set; }
        public Nullable<int> q_cli_total { get; set; }
        public Nullable<int> porc { get; set; }
    }
}
