//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netmefy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ot_x_fh_creacion
    {
        public string zona { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> cant_ot { get; set; }
    }
}
