//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netmefy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_stats_x_zona
    {
        public int id { get; set; }
        public string zona { get; set; }
        public Nullable<int> reclamos { get; set; }
        public Nullable<int> solicitudes { get; set; }
        public Nullable<decimal> velocidad { get; set; }
        public Nullable<decimal> promedio { get; set; }
        public Nullable<int> cantidadClientes { get; set; }
        public Nullable<decimal> edadPromedio { get; set; }
        public Nullable<int> dispositivos { get; set; }
    }
}
