//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netmefy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_top_clientes_ot
    {
        public string id { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string tipo_casa { get; set; }
        public string localidad { get; set; }
        public string zona { get; set; }
        public string provincia { get; set; }
        public string pais { get; set; }
        public Nullable<int> cant_reclamos { get; set; }
    }
}
