//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netmefy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_top_paginas_x_zona
    {
        public string pagina { get; set; }
        public string zona { get; set; }
        public Nullable<int> cant_mujeres { get; set; }
        public Nullable<int> cant_hombres { get; set; }
        public Nullable<int> cant_total { get; set; }
        public Nullable<int> edad_prom { get; set; }
    }
}
